# Generated by Django 4.2.1 on 2023-05-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cust', models.CharField(max_length=5)),
                ('nama_cust', models.CharField(max_length=30)),
                ('alamat', models.TextField()),
                ('hp', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tb_customer',
            },
        ),
    ]
