# Generated by Django 4.2.1 on 2023-05-24 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_faktur', models.IntegerField()),
                ('tgl_masuk', models.DateTimeField()),
                ('batas_waktu', models.DateTimeField()),
                ('tgl_bayar', models.DateTimeField()),
                ('jumlah', models.IntegerField()),
                ('harga', models.FloatField()),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('proses', 'Proses'), ('selesai', 'Selesai'), ('diambil', 'Diambil')], max_length=10)),
                ('dibayar', models.CharField(choices=[('dibayar', 'Dibayar'), ('belum_dibayar', 'Belum Dibayar')], max_length=15)),
                ('jumlah_bayar', models.FloatField()),
                ('id_cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'tb_transaksi',
            },
        ),
    ]
