# Generated by Django 3.2.16 on 2023-05-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='jumlah_bayar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
